### ISSUE TITLE
Low Priority Updates

### ISSUE THREAD

**Issue by thomasmholder** [VIP-LES/EosLib#18]
This is an issue to consolidate little changes that aren't immediately mission critical, but should be addressed at some point. Anyone is welcome to add them and we'll get around to them when we don't have a launch looming.

- Organize test suite and parametrize a bunch of the tests that can be
- Add more elegant handling of packets without transmit headers in packet string encoding/decoding
- I'm pretty sure if a body ever contains a utf-8 comma, it'll completely break parsing of it
- We could break up PacketFormatError into slightly more granular exceptions and add more descriptive text
- Validation logic should be added to setter functions so that exceptions are raised at the time they are caused

**Comment by DarylDohner** [comment]
Followup items from #14:
-actually move EosLib.packet.definitions.PacketDevice to EosLib.Device
-add my name to the contributors file, apparently I did a ticket on this repo (#9)

**Comment by thomasmholder** [comment]
Followup items from #21:

- Enable decoding from an old version
- Add validation functions for class data types (Device etc.)

**Comment by thomasmholder** [comment]
- Update readme to reflect changes made in #21

**Comment by thomasmholder** [comment]
https://github.com/VIP-LES/EosPayload/pull/23#discussion_r1038238950

**Comment by thomasmholder** [comment]
Fix the need to write "EosLib.packet.packet.Packet" ever again

**Comment by thomasmholder** [comment]
Add test driver devices
