### ISSUE TITLE
Higher Priority Items

### ISSUE THREAD

**Issue by DarylDohner** [VIP-LES/EosLib#24]
- **Make Destination field on data header optional**
- Add GROUND_STATION_# to devices list
- Add MISC_TEST_# to devices list
- Make it so a device value of 0 does not map to an actual device (ie, either no device is assigned id 0, or 0 maps to something like "BROADCAST" or "NOBODY_IN_PARTICULAR" [lol])
- Currently all the fields on the data header are nullable in the ctor, but the validate method will not take None for an answer.  I imagine transmit header works the same

**Comment by DarylDohner** [comment]
@thomasmholder thoughts?

**Comment by DarylDohner** [comment]
Also add devices for I2C_DRIVER and ADC_DRIVER, unless we think they fall under MISC_SENSOR_#

**Comment by thomasmholder** [comment]
I2C and ADC driver can definitely fit under MISC_SENSOR_#, the idea with adding so many is not having to update the list super often. That said I'm not super wild about how we're handling device IDs so maybe we should take another look at that.

**Comment by DarylDohner** [comment]
It's less-than-ideal but having an exhaustive devices list in EosLib seems to be the best way to make sure the payload and ground station are on the same page about who's who.  The only other way I can think of is to make a communications-based discovery protocol which gets real messy real fast due to our connection being super unreliable.

A refactor that could ease some of this would be to rename this list DeviceType and remove all the duplicates.  Then the DeviceID field on a driver is just some unique integer used to disambiguate between devices of the same type on the same system

That being said, we likely need to make a slightly more complicated addressing system anyway for the future so we could support multiple payloads and ground stations.  Probably the end result would be a specific device being identified by an address string like "1:7:3" mapping to System=1, Device Type=7, ID=3
