### ISSUE TITLE
String Handling Enhancements

### ISSUE THREAD

**Issue by thomasmholder** [VIP-LES/EosLib#31]
Right now, EosLib doesn't handle strings very well. This is somewhat by design, they're really inefficient so using strings should be discouraged, but there is occasionally a use case.

The following enhancements are definitely needed:

-  Add more elegant handling of packets without transmit headers in packet string encoding/decoding
- Add a static helper function to truncate strings to the maximum allowed body size
- Update string-related docstrings to reflect new fields
- Decode from string functions don't handle commas in the body well, fix that

**Comment by DarylDohner** [comment]
closed as not needed due to https://github.com/VIP-LES/EosLib/issues/57
