### ISSUE TITLE
Expand device list

### ISSUE THREAD

**Issue by thomasmholder** [VIP-LES/EosLib#36]
We need to figure out as comprehensive a list of devices as we can, and then add a bunch of misc and test driver IDs

**Comment by DarylDohner** [comment]
include IDs for SPOT and APRS per https://github.com/VIP-LES/EosGround/issues/8

**Comment by thomasmholder** [comment]
APRS makes some sense, but what is the use case for a Spot device ID?

**Comment by DarylDohner** [comment]
Spot is a valid telemetry data source that we can integrate into the ground station

**Comment by thomasmholder** [comment]
Should ground station specific components have a Device ID?

**Comment by DarylDohner** [comment]
Could be useful for storing the api results in a DB so we can track the source

**Comment by thomasmholder** [comment]
That's a good enough reason for me
